### ISSUE TITLE
Possibility for an update?

### ISSUE THREAD

**Issue by L-m-b** [Daniel-Griffiths/vapour#101]
Would be great to see this project flourish into something useful, i have isntalled it and the library/home section works and launches games! would be good to see the rest of the program be built up.

**Comment by Daniel-Griffiths** [comment]
Anything specific you would like to see added? I've uploaded a 2.0 version to finally bring it up to date, but the features are the same as before.

**Comment by L-m-b** [comment]
Well thoughts I had a while ago now was that it'd be awesome if it didn't depend on steam.
 the overbuilt UI of steam is just a clunker to use, if this could also install games off of steam somehow it'd be an idea for future updates, but I'll have to give it another go and give myself a refresher as I last tried this 8 months ago. And I believe it may have been slightly broken at the time. Will let you know.

**Comment by Daniel-Griffiths** [comment]
That's a good point, even the new version still relies on Steam to download/start games. I'm not sure if it's possible to avoid that but I'll take a look!

**Comment by L-m-b** [comment]
Cheers for that. Also. took a look at the new version, pretty impressed with it working other than the whole relying on steam thing.

However a little critique; I see that you have to log in to the chat separate to the client, which is fine and well but there is no alternative styling/declutter on the UI as it is just displaying the website.

My question is, if you can inject CSS or modify/inject HTML, would you in any way be able to change the coloring and remove the header bar in the least? 
It would save having a bonus store/library button in the way and make the chat less of an eye-sore.
![image](https://github.com/user-attachments/assets/dc2c3105-0690-4603-aae3-08cfa7aaf863)

Regardless of that, i appreciate the fact that you have revisited the project and gotten it up to date for your users, lots of projects just never get touched again and its kinda refreshing. kudos for making the steps to an alternative client, in time i hope you get more traction here and can improve your app.

**Comment by Ohrwerk** [comment]
Nice to read a sign of life here.
I'm glad there's been an update.

Here is my feedback:
• Windows XP Retro PC:  Setup reports that Vapour requires at least Windos 7 or higher.
• Windows 7 Retro PC:  Setup installs Vapour, but Windows reports that vapour.exe is not a valid Win32 application.
This is probably due to Chrome, nothing can be done. So also no client for old retro computers. Would have been too nice.
Unfortunately my test ends at this point.

Happy Coding

**Comment by Daniel-Griffiths** [comment]
Thanks both! I've made some small updates based on the feedback. 

- Header is now hidden on chat view
- Added support for 32 bit Windows (Although I don't have any machines to test this on)

I've deleted and reuploaded the existing 2.0 version, the windows exe should be larger now since the installer contains both 32 and 64 bit versions.

Since the webview component now supports `injectedCSS` it's pretty easy to modify the styles of any embedded steam pages if needed.

```
    <Webview
      src="https://steamcommunity.com/chat"
      injectedCSS="[class^='main_SteamPageHeader_']{ display: none !important;}"
    />
```

**Comment by Daniel-Griffiths** [comment]
One thing to consider is that this app still relies on Steam itself to install/launch games so it might not be useable on older OS's since Steam is no longer supported. 

You guys might also be interested in this project: https://github.com/OpenSteamClient/OpenSteamClient/tree/c%23-remake

It's not finished yet but it aims to make a client that is completly independant from Steam, he's rebuilding it in C# so it should be possible to port to windows in the future.
